name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t07&#45;01&#45;01
      id: t07-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: |
          lecturer-add#0130058501#Parmonangan Rotua Togatorop#PAT#mona.togatorop@del.ac.id#Information Systems
          lecturer-add#0114129002#Iustisia Natalia Simbolon#IUS#iustisia.simbolon@del.ac.id#Informatics
          lecturer-add#0124108201#Rosni Lumbantoruan#RSL#rosni@del.ac.id#Information Systems
          course-add#12S2102#Basisdata#4#C
          course-open#12S2102#2021/2022#odd#PAT,IUS,RSL
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          enrollment-add#12S2102#12S20001#2021/2022#odd
          enrollment-add#12S2102#12S20002#2021/2022#odd
          enrollment-grade#12S2102#12S20001#2021/2022#odd#BC
          enrollment-grade#12S2102#12S20002#2021/2022#odd#A
          enrollment-remedial#12S2102#12S20001#2021/2022#odd#B
          student-details#12S20001
          student-details#12S20002
          ---
        expected-output: |
          12S20001|Marcelino Manalu|2020|Information Systems|3.00|4
          12S20002|Yoga Sihombing|2020|Information Systems|4.00|4
          0130058501|Parmonangan Rotua Togatorop|PAT|mona.togatorop@del.ac.id|Information Systems
          0114129002|Iustisia Natalia Simbolon|IUS|iustisia.simbolon@del.ac.id|Informatics
          0124108201|Rosni Lumbantoruan|RSL|rosni@del.ac.id|Information Systems
          12S2102|Basisdata|4|C
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S2102|12S20001|2021/2022|odd|B(BC)
          12S2102|12S20002|2021/2022|odd|A
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t07&#45;01&#45;02
      id: t07-45-01-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;02
        setup-command: make compile
        command: make -s test_01
        input: |
          lecturer-add#0114129002#Iustisia Natalia Simbolon#IUS#iustisia.simbolon@del.ac.id#Informatics
          course-add#12S1101#Dasar Sistem Informasi#3#D
          course-open#12S1101#2020/2021#odd#IUS
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          student-add#12S20003#Marcel Simanjuntak#2020#Information Systems
          enrollment-add#12S1101#12S20001#2020/2021#odd
          enrollment-add#12S1101#12S20002#2020/2021#odd
          enrollment-add#12S1101#12S20003#2020/2021#odd
          enrollment-remedial#12S1101#12S20003#2020/2021#odd#A
          enrollment-grade#12S1101#12S20001#2020/2021#odd#B
          enrollment-grade#12S1101#12S20002#2020/2021#odd#B
          enrollment-grade#12S1101#12S20003#2020/2021#odd#B
          student-details#12S20001
          student-details#12S20002
          student-details#12S20003
          enrollment-remedial#12S1101#12S20003#2020/2021#odd#AB
          student-details#12S20003
          ---
        expected-output: |
          12S20001|Marcelino Manalu|2020|Information Systems|3.00|3
          12S20002|Yoga Sihombing|2020|Information Systems|3.00|3
          12S20003|Marcel Simanjuntak|2020|Information Systems|3.00|3
          12S20003|Marcel Simanjuntak|2020|Information Systems|3.50|3
          0114129002|Iustisia Natalia Simbolon|IUS|iustisia.simbolon@del.ac.id|Informatics
          12S1101|Dasar Sistem Informasi|3|D
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S20003|Marcel Simanjuntak|2020|Information Systems
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|AB(B)
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t07&#45;01&#45;03
      id: t07-45-01-45-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;03
        setup-command: make compile
        command: make -s test_01
        input: |
          lecturer-add#0130058501#Parmonangan Rotua Togatorop#PAT#mona.togatorop@del.ac.id#Information Systems
          lecturer-add#0114129002#Iustisia Natalia Simbolon#IUS#iustisia.simbolon@del.ac.id#Informatics
          lecturer-add#0124108201#Rosni Lumbantoruan#RSL#rosni@del.ac.id#Information Systems
          course-add#12S1101#Dasar Sistem Informasi#3#D
          course-add#12S2102#Basisdata#4#C
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          student-add#12S20003#Marcel Simanjuntak#2020#Information Systems
          course-open#12S1101#2020/2021#odd#IUS
          enrollment-add#12S1101#12S20001#2020/2021#odd
          enrollment-add#12S1101#12S20002#2020/2021#odd
          enrollment-add#12S1101#12S20003#2020/2021#odd
          enrollment-grade#12S1101#12S20001#2020/2021#odd#B
          enrollment-remedial#12S1101#12S20001#2020/2021#odd#B
          enrollment-grade#12S1101#12S20002#2020/2021#odd#B
          enrollment-grade#12S1101#12S20003#2020/2021#odd#B
          student-details#12S20003
          enrollment-remedial#12S1101#12S20003#2020/2021#odd#AB
          course-open#12S2102#2021/2022#odd#PAT,IUS,RSL
          enrollment-add#12S2102#12S20001#2021/2022#odd
          enrollment-add#12S2102#12S20002#2021/2022#odd
          enrollment-add#12S2102#12S20003#2021/2022#odd
          enrollment-grade#12S2102#12S20001#2021/2022#odd#B
          enrollment-grade#12S2102#12S20002#2021/2022#odd#AB
          enrollment-grade#12S2102#12S20003#2021/2022#odd#BC
          student-details#12S20001
          course-open#12S2102#2022/2023#odd#IUS,RSL
          enrollment-add#12S2102#12S20003#2022/2023#odd
          enrollment-grade#12S2102#12S20003#2022/2023#odd#AB
          enrollment-remedial#12S2102#12S20003#2022/2023#odd#B
          student-details#12S20001
          student-details#12S20002
          student-details#12S20003
          ---
        expected-output: |
          12S20003|Marcel Simanjuntak|2020|Information Systems|3.00|3
          12S20001|Marcelino Manalu|2020|Information Systems|3.00|7
          12S20001|Marcelino Manalu|2020|Information Systems|3.00|7
          12S20002|Yoga Sihombing|2020|Information Systems|3.29|7
          12S20003|Marcel Simanjuntak|2020|Information Systems|3.21|7
          0130058501|Parmonangan Rotua Togatorop|PAT|mona.togatorop@del.ac.id|Information Systems
          0114129002|Iustisia Natalia Simbolon|IUS|iustisia.simbolon@del.ac.id|Informatics
          0124108201|Rosni Lumbantoruan|RSL|rosni@del.ac.id|Information Systems
          12S1101|Dasar Sistem Informasi|3|D
          12S2102|Basisdata|4|C
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S20003|Marcel Simanjuntak|2020|Information Systems
          12S1101|12S20001|2020/2021|odd|B(B)
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|AB(B)
          12S2102|12S20001|2021/2022|odd|B
          12S2102|12S20002|2021/2022|odd|AB
          12S2102|12S20003|2021/2022|odd|BC
          12S2102|12S20003|2022/2023|odd|B(AB)
        comparison-method: contains
        timeout: 1
        max-score: 10
    - name: t07&#45;01&#45;04
      id: t07-45-01-45-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;04
        setup-command: make compile
        command: make -s test_01
        input: |
          lecturer-add#0130058501#Parmonangan Rotua Togatorop#PAT#mona.togatorop@del.ac.id#Information Systems
          lecturer-add#0114129002#Iustisia Natalia Simbolon#IUS#iustisia.simbolon@del.ac.id#Informatics
          lecturer-add#0124108201#Rosni Lumbantoruan#RSL#rosni@del.ac.id#Information Systems
          course-add#12S1101#Dasar Sistem Informasi#3#D
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          student-add#12S20003#Marcel Simanjuntak#2020#Information Systems
          course-open#12S1101#2020/2021#odd#IUS
          enrollment-add#12S1101#12S20001#2020/2021#odd
          enrollment-add#12S1101#12S20002#2020/2021#odd
          enrollment-add#12S1101#12S20003#2020/2021#odd
          enrollment-grade#12S1101#12S20001#2020/2021#odd#B
          enrollment-grade#12S1101#12S20002#2020/2021#odd#B
          enrollment-grade#12S1101#12S20003#2020/2021#odd#B
          course-open#12S1101#2020/2021#even#IUS
          course-open#12S1101#2021/2022#odd#IUS
          enrollment-add#12S1101#12S20002#2021/2022#odd
          enrollment-add#12S1101#12S20003#2021/2022#odd
          enrollment-grade#12S1101#12S20002#2021/2022#odd#AB
          enrollment-grade#12S1101#12S20003#2021/2022#odd#AB
          enrollment-add#12S1101#12S20001#2020/2021#even
          enrollment-add#12S1101#12S20002#2020/2021#even
          enrollment-add#12S1101#12S20003#2020/2021#even
          enrollment-grade#12S1101#12S20001#2020/2021#even#AB
          enrollment-grade#12S1101#12S20002#2020/2021#even#A
          enrollment-grade#12S1101#12S20003#2020/2021#even#A
          course-history#12S1101
          find-the-best-student#2020/2021#odd
          find-the-best-student#2020/2021#even
          add-best-student#best-student
          ---
        expected-output: |-
          12S1101|Dasar Sistem Informasi|3|D|2020/2021|odd|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|B
          12S1101|Dasar Sistem Informasi|3|D|2021/2022|odd|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20002|2021/2022|odd|AB
          12S1101|12S20003|2021/2022|odd|AB
          12S1101|Dasar Sistem Informasi|3|D|2020/2021|even|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20001|2020/2021|even|AB
          12S1101|12S20002|2020/2021|even|A
          12S1101|12S20003|2020/2021|even|A
          0130058501|Parmonangan Rotua Togatorop|PAT|mona.togatorop@del.ac.id|Information Systems
          0114129002|Iustisia Natalia Simbolon|IUS|iustisia.simbolon@del.ac.id|Informatics
          0124108201|Rosni Lumbantoruan|RSL|rosni@del.ac.id|Information Systems
          12S1101|Dasar Sistem Informasi|3|D
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S20003|Marcel Simanjuntak|2020|Information Systems
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|B
          12S1101|12S20002|2021/2022|odd|AB
          12S1101|12S20003|2021/2022|odd|AB
          12S1101|12S20001|2020/2021|even|AB
          12S1101|12S20002|2020/2021|even|A
          12S1101|12S20003|2020/2021|even|A
          12S20002|B/A
          12S20002|B/A
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: t07&#45;01&#45;5
      id: t07-45-01-45-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;5
        setup-command: make compile
        command: make -s test_01
        input: |
          lecturer-add#0130058501#Parmonangan Rotua Togatorop#PAT#mona.togatorop@del.ac.id#Information Systems
          lecturer-add#0114129002#Iustisia Natalia Simbolon#IUS#iustisia.simbolon@del.ac.id#Informatics
          lecturer-add#0124108201#Rosni Lumbantoruan#RSL#rosni@del.ac.id#Information Systems
          course-add#12S1101#Dasar Sistem Informasi#3#D
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          student-add#12S20003#Marcel Simanjuntak#2020#Information Systems
          course-open#12S1101#2020/2021#odd#IUS
          enrollment-add#12S1101#12S20001#2020/2021#odd
          enrollment-add#12S1101#12S20002#2020/2021#odd
          enrollment-add#12S1101#12S20003#2020/2021#odd
          enrollment-grade#12S1101#12S20001#2020/2021#odd#B
          enrollment-grade#12S1101#12S20002#2020/2021#odd#B
          enrollment-grade#12S1101#12S20003#2020/2021#odd#B
          course-open#12S1101#2020/2021#even#IUS
          course-open#12S1101#2021/2022#odd#IUS
          enrollment-add#12S1101#12S20002#2021/2022#odd
          enrollment-add#12S1101#12S20003#2021/2022#odd
          enrollment-grade#12S1101#12S20002#2021/2022#odd#C
          enrollment-grade#12S1101#12S20003#2021/2022#odd#AB
          enrollment-remedial#12S1101#12S20002#2021/2022#odd#B
          enrollment-add#12S1101#12S20001#2020/2021#even
          enrollment-add#12S1101#12S20002#2020/2021#even
          enrollment-add#12S1101#12S20003#2020/2021#even
          enrollment-grade#12S1101#12S20001#2020/2021#even#BC
          enrollment-grade#12S1101#12S20002#2020/2021#even#A
          enrollment-grade#12S1101#12S20003#2020/2021#even#A
          enrollment-remedial#12S1101#12S20001#2020/2021#even#AB
          course-history#12S1101
          find-the-best-student#2020/2021#odd
          find-the-best-student#2020/2021#even
          add-best-student#best-student
          ---
        expected-output: |-
          12S1101|Dasar Sistem Informasi|3|D|2020/2021|odd|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|B
          12S1101|Dasar Sistem Informasi|3|D|2021/2022|odd|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20002|2021/2022|odd|B(C)
          12S1101|12S20003|2021/2022|odd|AB
          12S1101|Dasar Sistem Informasi|3|D|2020/2021|even|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20001|2020/2021|even|AB(BC)
          12S1101|12S20002|2020/2021|even|A
          12S1101|12S20003|2020/2021|even|A
          0130058501|Parmonangan Rotua Togatorop|PAT|mona.togatorop@del.ac.id|Information Systems
          0114129002|Iustisia Natalia Simbolon|IUS|iustisia.simbolon@del.ac.id|Informatics
          0124108201|Rosni Lumbantoruan|RSL|rosni@del.ac.id|Information Systems
          12S1101|Dasar Sistem Informasi|3|D
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S20003|Marcel Simanjuntak|2020|Information Systems
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|B
          12S1101|12S20002|2021/2022|odd|B(C)
          12S1101|12S20003|2021/2022|odd|AB
          12S1101|12S20001|2020/2021|even|AB(BC)
          12S1101|12S20002|2020/2021|even|A
          12S1101|12S20003|2020/2021|even|A
          12S20002|B/A
          12S20002|B/A
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t07&#45;01&#45;6
      id: t07-45-01-45-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;6
        setup-command: make compile
        command: make -s test_01
        input: |-
          lecturer-add#0130058501#Parmonangan Rotua Togatorop#PAT#mona.togatorop@del.ac.id#Information Systems
          lecturer-add#0114129002#Iustisia Natalia Simbolon#IUS#iustisia.simbolon@del.ac.id#Informatics
          lecturer-add#0124108201#Rosni Lumbantoruan#RSL#rosni@del.ac.id#Information Systems
          course-add#12S1101#Dasar Sistem Informasi#3#D
          student-add#12S20001#Marcelino Manalu#2020#Information Systems
          student-add#12S20002#Yoga Sihombing#2020#Information Systems
          student-add#12S20003#Marcel Simanjuntak#2020#Information Systems
          course-open#12S1101#2020/2021#odd#IUS
          enrollment-add#12S1101#12S20001#2020/2021#odd
          enrollment-add#12S1101#12S20002#2020/2021#odd
          enrollment-add#12S1101#12S20003#2020/2021#odd
          enrollment-grade#12S1101#12S20001#2020/2021#odd#B
          enrollment-grade#12S1101#12S20002#2020/2021#odd#B
          enrollment-grade#12S1101#12S20003#2020/2021#odd#B
          course-open#12S1101#2020/2021#even#IUS
          course-open#12S1101#2021/2022#odd#IUS
          enrollment-add#12S1101#12S20002#2021/2022#odd
          enrollment-add#12S1101#12S20003#2021/2022#odd
          enrollment-grade#12S1101#12S20002#2021/2022#odd#C
          enrollment-grade#12S1101#12S20003#2021/2022#odd#AB
          enrollment-remedial#12S1101#12S20002#2021/2022#odd#B
          enrollment-add#12S1101#12S20001#2020/2021#even
          enrollment-add#12S1101#12S20002#2020/2021#even
          enrollment-add#12S1101#12S20003#2020/2021#even
          enrollment-grade#12S1101#12S20001#2020/2021#even#BC
          enrollment-grade#12S1101#12S20002#2020/2021#even#A
          enrollment-grade#12S1101#12S20003#2020/2021#even#A
          enrollment-remedial#12S1101#12S20001#2020/2021#even#AB
          course-history#12S1101
          find-the-best-student#2020/2021#odd
          find-the-best-student#2020/2021#even
          add-best-student#best-student
          ---
        expected-output: |-
          12S1101|Dasar Sistem Informasi|3|D|2020/2021|odd|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|B
          12S1101|Dasar Sistem Informasi|3|D|2021/2022|odd|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20002|2021/2022|odd|B(C)
          12S1101|12S20003|2021/2022|odd|AB
          12S1101|Dasar Sistem Informasi|3|D|2020/2021|even|IUS (iustisia.simbolon@del.ac.id)
          12S1101|12S20001|2020/2021|even|AB(BC)
          12S1101|12S20002|2020/2021|even|A
          12S1101|12S20003|2020/2021|even|A
          0130058501|Parmonangan Rotua Togatorop|PAT|mona.togatorop@del.ac.id|Information Systems
          0114129002|Iustisia Natalia Simbolon|IUS|iustisia.simbolon@del.ac.id|Informatics
          0124108201|Rosni Lumbantoruan|RSL|rosni@del.ac.id|Information Systems
          12S1101|Dasar Sistem Informasi|3|D
          12S20001|Marcelino Manalu|2020|Information Systems
          12S20002|Yoga Sihombing|2020|Information Systems
          12S20003|Marcel Simanjuntak|2020|Information Systems
          12S1101|12S20001|2020/2021|odd|B
          12S1101|12S20002|2020/2021|odd|B
          12S1101|12S20003|2020/2021|odd|B
          12S1101|12S20002|2021/2022|odd|B(C)
          12S1101|12S20003|2021/2022|odd|AB
          12S1101|12S20001|2020/2021|even|AB(BC)
          12S1101|12S20002|2020/2021|even|A
          12S1101|12S20003|2020/2021|even|A
          12S20002|B/A
          12S20002|B/A
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T07-45-01-45-01_RESULTS: "${{steps.t07-45-01-45-01.outputs.result}}"
        T07-45-01-45-02_RESULTS: "${{steps.t07-45-01-45-02.outputs.result}}"
        T07-45-01-45-03_RESULTS: "${{steps.t07-45-01-45-03.outputs.result}}"
        T07-45-01-45-04_RESULTS: "${{steps.t07-45-01-45-04.outputs.result}}"
        T07-45-01-45-5_RESULTS: "${{steps.t07-45-01-45-5.outputs.result}}"
        T07-45-01-45-6_RESULTS: "${{steps.t07-45-01-45-6.outputs.result}}"
      with:
        runners: t07-45-01-45-01,t07-45-01-45-02,t07-45-01-45-03,t07-45-01-45-04,t07-45-01-45-5,t07-45-01-45-6
